### ISSUE TITLE
make failure on Ubuntu

### ISSUE THREAD

**Issue by josefnpat** [urraka/texpack#10]
Howdy! I usually build and use this on arch, but I noticed that on ubuntu, it doesn't compile :sob: 

_as a sidenote, the `sudo` line for the ubuntu dependencies in the docs probably doesn't need to be commented out_

	~/repos/texpack♠ cat /etc/issue
	Ubuntu 14.04.1 LTS \n \l

	~/repos/texpack♠ uname -a
	Linux seppi-Aspire-E3-111 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
	~/repos/texpack♠ sudo apt-get install libpng12-dev
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	The following extra packages will be installed:
	  zlib1g-dev
	The following NEW packages will be installed:
	  libpng12-dev zlib1g-dev
	0 upgraded, 2 newly installed, 0 to remove and 245 not upgraded.
	Need to get 389 kB of archives.
	After this operation, 1,124 kB of additional disk space will be used.
	Do you want to continue? [Y/n] 
	Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main zlib1g-dev amd64 1:1.2.8.dfsg-1ubuntu1 [183 kB]
	Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty/main libpng12-dev amd64 1.2.50-1ubuntu2 [206 kB]
	Fetched 389 kB in 0s (411 kB/s)   
	Selecting previously unselected package zlib1g-dev:amd64.
	(Reading database ... 199480 files and directories currently installed.)
	Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-1ubuntu1_amd64.deb ...
	Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
	Selecting previously unselected package libpng12-dev.
	Preparing to unpack .../libpng12-dev_1.2.50-1ubuntu2_amd64.deb ...
	Unpacking libpng12-dev (1.2.50-1ubuntu2) ...
	Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
	Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
	Setting up libpng12-dev (1.2.50-1ubuntu2) ...
	~/repos/texpack♠ make
	g++ src/main.cpp src/packer.cpp src/bleeding.cpp src/png/png.cpp src/rbp/MaxRects.cpp  -g -O2 -Wall -std=c++11   -lpng -lz -o bin/texpack
	In file included from /usr/include/png.h:540:0,
			 from src/png/png.cpp:5:
	/usr/include/pngconf.h:371:12: error: ‘__pngconf’ does not name a type
		    __pngconf.h__ in libpng already includes setjmp.h;
		    ^
	/usr/include/pngconf.h:372:12: error: ‘__dont__’ does not name a type
		    __dont__ include it again.;
		    ^
	make: *** [bin/texpack] Error 1

**Comment by urraka** [comment]
Can you try if adding `#define PNG_SKIP_SETJMP_CHECK` at the top of `src/png/png.cpp` fixes this problem?

**Comment by josefnpat** [comment]
I did as you asked, and `texpack` now builds, installs and works perfectly!

**Comment by urraka** [comment]
I guess I was wrong then. I thought it was using a transform flag that was added in 1.4. Anyway, closing this now that it works. Thanks for the help!

**Comment by josefnpat** [comment]
<3 Thanks for the awesome util!
