### ISSUE TITLE
[suggestion] max-size parameter as a boolean 

### ISSUE THREAD

**Issue by rraallvv** [urraka/texpack#13]
I'm porting your texture packer to use as a script in a Photoshop tool and found out that the code could be re-factured to accept max-size as a boolean parameter and then take the values in the parameter size as maximum values accordingly, in order to keep things a bit simpler in the UI that allows the user to enter those values.

Keep up the good work.

**Comment by urraka** [comment]
I agree that it makes more sense that way so I went ahead and changed --max-size to be a boolean flag. Thanks for the suggestion!

**Comment by rraallvv** [comment]
@urraka I was able to port your modifications to JavasScript with ease, thank you so much. It’s very appreciated.
