### ISSUE TITLE
Global metadata

### ISSUE THREAD

**Issue by nthapaliya** [urraka/texpack#16]
There is per-object metadata, but I was wondering if it was possible to add lines to the global metadata, the "meta" hash at the bottom of the file? 

Using texturepacker I was able to specify a value "scale": "4" that my library was able to understand and scale accordingly. I didn't find anything specific in the docs.

**Comment by urraka** [comment]
There's no way to add global metadata currently. The metadata file is basically a list of `filename: metadata`. Perhaps I could add a magic filename for global info, like ".global". Any better ideas on how to go about this are welcome :)

**Comment by urraka** [comment]
Implemented this with the ".global" file name like I said for now. The value for that .global entry should be an object. Its members will end up along with the rest of the "meta" properties.

**Comment by nthapaliya** [comment]
Thank you for the prompt reply. That is exactly what I was looking for! Tried it and works like a charm.

(btw .global is better than 'meta' which I was initially thinking about, which could theoretically  be a filename)
