### ISSUE TITLE
Trim feature

### ISSUE THREAD

**Issue by josefnpat** [urraka/texpack#9]
So I'm using this library, and it's working great!

I noticed there wasn't a trim feature, so I've started hacking a workaround:

    #!/bin/sh

    TEXPACK="/home/seppi/repos/texpack/bin/texpack"
    TEMP=`mktemp -d`
    NAME="ships"
    CWD=`pwd`

    rm $NAME*.png
    rm $NAME*.json

    for file in *.png
    do
      convert $file -trim +repage $TEMP/$file
    done

    cd $TEMP
    ls $TEMP/*.png > image_list.txt
    $TEXPACK --padding=2 -e image_list.txt --output=$NAME --max-size=512x512
    mv $NAME* $CWD
    cd $CWD

    rm $TEMP -rf

While this works well enough for my purposes, the `ships.json` output doesn't have the images original size (due to `convert` trimming it).

What would be *amazing* is if there was a `--trim` flag of some sort that I could use, that would mention the images original size, and it's current dimensions in the atlas.

Otherwise I can probably hack something together, but it wouldn't be pretty :cry:

**Comment by urraka** [comment]
I'm glad you found this little tool useful :)

I had this trim feature in mind as well so I decided to implement it. I tested it rather quickly so let me know if you find any problems. With the `--trim` flag it should remove transparent borders and you will get these additional properties in the output json file: `real_width`, `real_height`, `xoffset` and `yoffset`.

**Comment by josefnpat** [comment]
Oh my god you have made my day.... <3

It works fantastically!


![ships](https://cloud.githubusercontent.com/assets/646162/6219967/57275d34-b5fe-11e4-95e2-4f1befcb1a09.png)

http://pastebin.com/raw.php?i=TYGCrBuH
